# .bashrc
# enable bash completion in interactive shells
if ! shopt -oq posix; then
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

## Use rspecific aliases and functions
#export GTK_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus
#export QT_IM_MODULE=ibus
##export GNUTERM="wxt"

# colored ls output
export LS_OPTIONS='--color=auto'

# include .bashrc_aliases if it exists
if [ -f $HOME/dev/dotfiles/personal/bashrc_extras ]; then
    . $HOME/dev/dotfiles/personal/bashrc_extras
fi

