#
# Status Bar:
#
# Read `man 5 sway-bar` for more information about this section.
bar {
    position top
    status_command i3status-rs ~/.config/i3status-rust/config.toml

    colors {
    	# NOTE: last two digits of background set opacity
	# (decimal precent) x 255 = decimal number --> to HEX
	#
	# Examples for 60% and 88% opacity
	# 100*255 =  				FF (224 converted to HEX)
	# 0.90*255 =  				E6 (224 converted to HEX)
	# 0.90*255 =  				E6 (224 converted to HEX)
	# 0.88*255 = 224.4 --> 224 (floor) --> 	E0 (224 converted to HEX)
	# 0.85*255 =  				D9 (224 converted to HEX)
	# 0.80*255 =  				CC (224 converted to HEX)
	# 0.60*255 = 153 --> 			99 (153 converted to HEX)
	#
        background #1F1F28E6
        statusline #DCD7BA
        separator  #54546D

        # state             border  bg      text
        focused_workspace   #2D4F67 #2D4F67 #DCD7BA
        active_workspace    #1F1F28 #1F1F28 #DCD7BA
        inactive_workspace  #1F1F28 #1F1F28 #727169
        urgent_workspace    #C34043 #C34043 #DCD7BA
    }
}
#
# Other bar related settings
#
# Enable floating, set size, and move to top-right corner
for_window [app_id="gsimplecal"] {
    floating enable
    border pixel 2
    sticky enable
    resize set 300px 200px
    move position 100ppt 0
    move left 240px
}
