enable_audio_bell no
font_size 11.0

tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 0
hide_window_decorations yes

clipboard_control write-clipboard write-primary read-clipboard read-primary

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# BEGIN_KITTY_THEME
# Kanagawa
include current-theme.conf
# END_KITTY_THEME
